package com.orangeandbronze.enlistment.domain;

public enum Time {
	MONTHUA, TUEFRIA, WEDSATA,
	MONTHUB, TUEFRIB, WEDSATB,
	MONTHUC, TUEFRIC, WEDSATC,
	MONTHUD, TUEFRID, WEDSATD,
	MONTHUE, TUEFRIE, WEDSATE,
	MONTHUF, TUEFRIF, WEDSATF
}
